name: federicoviceconti_github_io
description: My personal website build in Flutter with ❤️

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl: ^0.17.0
  provider: ^5.0.0
  fluttertoast: ^8.0.6
  url_launcher: ^6.0.3
  flutter_svg: ^0.22.0
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/