name: federicoviceconti_github_io
description: My personal website build in Flutter with ❤️

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: ^0.17.0
  provider: ^6.0.5
  fluttertoast: ^8.0.6
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.4
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/